version: "3.9"

services:

  # ── Banking Application ────────────────────────────────────────────────────
  banking-app:
    build: .
    container_name: banking-app
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs
    networks:
      - banking-net

networks:
  banking-net:
    driver: bridge
