"""
RCA agent — ReAct loop powered by Anthropic Claude.

Flow:
  1. Load incident from log_incidents via HealingDBAdapter
  2. Resolve the GitHub repo (service_repo_map → sub-agent discovery)
  3. ReAct loop: Claude calls GitHub tools iteratively
  4. Claude calls finish_rca → RCAReport is validated and returned
"""
import json
import logging
import uuid
from datetime import datetime, timezone
from typing import Callable

import anthropic

from config.settings import settings
from .cache import read_cache, write_cache, append_rca_history
from .github_tools import (
    get_commit_diff,
    get_commits_since,
    get_repo_file,
    list_repo_files,
    search_code_in_repo,
)
from .models import RCAReport
from .repo_resolver import RepoResolver

logger = logging.getLogger(__name__)


class _FinishRCA(Exception):
    def __init__(self, report: RCAReport):
        self.report = report


SYSTEM_PROMPT = """You are an expert Site Reliability Engineer performing rapid automated Root Cause Analysis (RCA) for a banking microservice application.

TARGET: Complete your full analysis in 4–6 tool calls. Be fast and decisive.

FAST-PATH PROCESS (follow in order):
1. [Call 1] Call search_code_in_repo with the exception class name or failing method from the error message. This finds the relevant source file directly — do NOT browse directories.
2. [Call 2] Call read_context_cache for the file found. On cache miss, call get_repo_file to read that file.
3. [Call 3] Call write_context_cache to save the fetched file content.
4. [Call 4] OPTIONAL — call get_commits_since ONLY if the incident timestamp strongly suggests a very recent code change caused it.
5. [Call 5] Call finish_rca with your complete structured report.

STRICT RULES — violating these wastes iterations:
- NEVER call list_repo_files. Use search_code_in_repo to locate files — it is faster and targeted.
- Read AT MOST 2 source files. Focus only on the file throwing the exception or containing the failing method.
- Always check read_context_cache before any GitHub call. Always write_context_cache after a successful fetch.
- Call finish_rca no later than your 6th tool call, even with partial evidence.
- If the file cannot be found, call finish_rca immediately with confidence "low" using error message analysis.
- Do NOT read test files, config files, DTOs, model classes, or repositories unless directly named in the stack trace.

CONFIDENCE:
- "high" = you read the exact file/line throwing the exception
- "medium" = you found closely related code that strongly implies the cause
- "low" = analysis from error message and exception type only (no code read)

RCA REPORT SCHEMA (pass as JSON to finish_rca):
{
  "schema_version": "1.0",
  "rca_id": "<auto-generated uuid4>",
  "error_log_id": "<from the input>",
  "service_name": "<service name>",
  "generated_at": "<ISO 8601 UTC>",
  "incident_summary": {
    "what": "<one sentence>",
    "when": "<ISO timestamp>",
    "environment": "<prod/staging/etc>",
    "severity": "<critical/high/medium/low>",
    "estimated_impact": "<optional>"
  },
  "timeline": [{"timestamp": "<ISO>", "event": "<description>"}],
  "root_cause": {
    "summary": "<clear explanation of what caused the error>",
    "confidence": "high|medium|low",
    "confidence_reason": "<why this confidence level>",
    "code_reference": {
      "file": "<path>",
      "line": <int or null>,
      "function": "<name or null>",
      "repo": "<repo name>",
      "commit_sha": "<sha or null>",
      "github_url": "<url or null>"
    },
    "regression_introduced_by": null
  },
  "contributing_factors": ["<factor>"],
  "evidence": [{"type": "code|diff|deployment|log", "description": "<desc>", "value": "<snippet>"}],
  "impact_assessment": {
    "affected_service": "<name>",
    "affected_environment": "<env>",
    "affected_functionality": "<optional>",
    "inferred_error_rate": "<optional>",
    "duration_estimate": "<optional>"
  },
  "suggested_solutions": [
    {"priority": 1, "effort": "quick-fix|medium|large", "title": "<title>", "description": "<desc>", "code_suggestion": "<optional>"}
  ],
  "prevention_recommendations": ["<recommendation>"],
  "analysis_metadata": {
    "model": "<model>",
    "react_iterations": 0,
    "github_files_fetched": [],
    "cache_hits": [],
    "deployment_record_used": false,
    "repo_discovered_via": "service_repo_map"
  }
}"""

TOOLS = [
    {
        "name": "get_repo_file",
        "description": "Fetch the full content of a file from a GitHub repository at a given ref. Always call read_context_cache first.",
        "input_schema": {
            "type": "object",
            "properties": {
                "org": {"type": "string", "description": "GitHub organisation or user name"},
                "repo": {"type": "string", "description": "Repository name"},
                "path": {"type": "string", "description": "File path within the repo"},
                "ref": {"type": "string", "description": "Branch name or commit SHA (default: main)", "default": "main"},
            },
            "required": ["org", "repo", "path"],
        },
    },
    {
        "name": "list_repo_files",
        "description": "List files and directories at a path in a GitHub repo. Use to explore structure before fetching files.",
        "input_schema": {
            "type": "object",
            "properties": {
                "org": {"type": "string"},
                "repo": {"type": "string"},
                "directory": {"type": "string", "description": "Directory path to list (empty = root)", "default": ""},
                "ref": {"type": "string", "default": "main"},
            },
            "required": ["org", "repo"],
        },
    },
    {
        "name": "search_code_in_repo",
        "description": "Search for a string, class, or method name within a GitHub repository.",
        "input_schema": {
            "type": "object",
            "properties": {
                "org": {"type": "string"},
                "repo": {"type": "string"},
                "query": {"type": "string", "description": "Search term or symbol"},
            },
            "required": ["org", "repo", "query"],
        },
    },
    {
        "name": "get_commit_diff",
        "description": "Get the full diff for a specific commit SHA. Key for identifying regressions.",
        "input_schema": {
            "type": "object",
            "properties": {
                "org": {"type": "string"},
                "repo": {"type": "string"},
                "commit_sha": {"type": "string"},
            },
            "required": ["org", "repo", "commit_sha"],
        },
    },
    {
        "name": "get_commits_since",
        "description": "List commits on a branch since a given timestamp.",
        "input_schema": {
            "type": "object",
            "properties": {
                "org": {"type": "string"},
                "repo": {"type": "string"},
                "branch": {"type": "string"},
                "since": {"type": "string", "description": "ISO 8601 timestamp"},
            },
            "required": ["org", "repo", "branch", "since"],
        },
    },
    {
        "name": "get_recent_deployments",
        "description": "Retrieve recent deployments for a service/environment. Returns empty if no CI/CD integration configured.",
        "input_schema": {
            "type": "object",
            "properties": {
                "service_name": {"type": "string"},
                "environment": {"type": "string"},
                "since_hours": {"type": "integer", "default": 48},
                "limit": {"type": "integer", "default": 5},
            },
            "required": ["service_name", "environment"],
        },
    },
    {
        "name": "get_service_metadata",
        "description": "Get metadata about a service.",
        "input_schema": {
            "type": "object",
            "properties": {"service_name": {"type": "string"}},
            "required": ["service_name"],
        },
    },
    {
        "name": "read_context_cache",
        "description": "Read a previously cached GitHub file or repo tree. ALWAYS call this before get_repo_file or list_repo_files.",
        "input_schema": {
            "type": "object",
            "properties": {
                "service_name": {"type": "string"},
                "cache_key": {"type": "string", "description": "Use 'file:<path>' for files, 'repo_tree' for directory listings"},
            },
            "required": ["service_name", "cache_key"],
        },
    },
    {
        "name": "write_context_cache",
        "description": "Persist a GitHub file or repo tree to cache. ALWAYS call this after a successful GitHub fetch.",
        "input_schema": {
            "type": "object",
            "properties": {
                "service_name": {"type": "string"},
                "cache_key": {"type": "string"},
                "content": {"type": "object", "description": "The content to cache"},
                "commit_sha": {"type": "string", "description": "Optional commit SHA"},
            },
            "required": ["service_name", "cache_key", "content"],
        },
    },
    {
        "name": "finish_rca",
        "description": "Submit the completed RCA report. This MUST be called to end the analysis.",
        "input_schema": {
            "type": "object",
            "properties": {
                "report": {
                    "type": "object",
                    "description": "Full RCA report object conforming to RCAReport schema",
                }
            },
            "required": ["report"],
        },
    },
]


class RCAAgent:
    def __init__(self, obs_adapter, cicd_adapter):
        self.obs = obs_adapter
        self.cicd = cicd_adapter
        self.client = anthropic.Anthropic(api_key=settings.ANTHROPIC_API_KEY)

    def _emit(self, callback: Callable[[dict], None] | None, event: dict) -> None:
        if callback is None:
            return
        try:
            event.setdefault("ts", datetime.now(timezone.utc).isoformat())
            callback(event)
        except Exception:
            pass

    def run(
        self,
        incident_id: str,
        trace_callback: Callable[[dict], None] | None = None,
        stop_check: Callable[[], bool] | None = None,
    ) -> RCAReport:
        # 1. Load incident
        error_log = self.obs.get_error_log(incident_id)

        self._emit(trace_callback, {
            "type": "start",
            "service": error_log.service_name,
            "error_type": error_log.error_type,
        })

        # 2. Resolve GitHub repo
        resolver = RepoResolver(self.cicd)
        repo_info = resolver.resolve(
            error_log.service_name, error_log.environment, error_log.occurred_at
        )
        logger.info(
            "Resolved repo for %s: %s/%s (via %s)",
            error_log.service_name,
            repo_info["org"],
            repo_info["repo"],
            repo_info["discovered_via"],
        )
        self._emit(trace_callback, {
            "type": "repo_resolved",
            "org": repo_info["org"],
            "repo": repo_info["repo"],
            "discovered_via": repo_info["discovered_via"],
        })

        # 3. Build initial context message for Claude
        error_context = {
            "incident_id": incident_id,
            "service_name": error_log.service_name,
            "environment": error_log.environment,
            "error_type": error_log.error_type,
            "error_message": error_log.error_message,
            "stack_trace": error_log.stack_trace,
            "severity": error_log.severity,
            "occurred_at": error_log.occurred_at.isoformat(),
            "metadata": error_log.metadata,
            "resolved_repo": repo_info,
        }

        messages = [
            {
                "role": "user",
                "content": (
                    "Perform a Root Cause Analysis for the following incident from the banking application. "
                    "Use the available tools to investigate the codebase, then call finish_rca.\n\n"
                    f"```json\n{json.dumps(error_context, indent=2, default=str)}\n```"
                ),
            }
        ]

        # 4. ReAct loop
        iterations = 0
        github_files_fetched: list[str] = []
        cache_hits: list[str] = []
        final_report: RCAReport | None = None
        max_iterations = settings.MAX_REACT_ITERATIONS

        while iterations < max_iterations:
            if stop_check and stop_check():
                raise RuntimeError("RCA job stopped by user.")
            iterations += 1
            logger.debug("ReAct iteration %d", iterations)

            response = self.client.messages.create(
                model=settings.CLAUDE_MODEL,
                max_tokens=4096,
                system=SYSTEM_PROMPT,
                tools=TOOLS,
                messages=messages,
            )

            messages.append({"role": "assistant", "content": response.content})

            for block in response.content:
                if hasattr(block, "type") and block.type == "text" and block.text.strip():
                    self._emit(trace_callback, {
                        "type": "reasoning",
                        "text": block.text.strip(),
                    })

            if response.stop_reason == "end_turn":
                logger.warning("Agent reached end_turn without calling finish_rca")
                break

            if response.stop_reason != "tool_use":
                logger.warning("Unexpected stop_reason: %s", response.stop_reason)
                break

            tool_results = []
            done = False

            for block in response.content:
                if block.type != "tool_use":
                    continue

                tool_name = block.name
                tool_input = block.input

                self._emit(trace_callback, {
                    "type": "tool_call",
                    "tool": tool_name,
                    "input": tool_input,
                })

                try:
                    result = self._dispatch(
                        tool_name, tool_input, error_log, repo_info,
                        github_files_fetched, cache_hits, trace_callback,
                    )
                except _FinishRCA as fin:
                    final_report = fin.report
                    done = True
                    tool_results.append({
                        "type": "tool_result",
                        "tool_use_id": block.id,
                        "content": json.dumps({"status": "rca_submitted"}),
                    })
                    break
                except Exception as exc:
                    logger.exception("Tool %s raised: %s", tool_name, exc)
                    result = {"error": str(exc)}

                self._emit(trace_callback, {
                    "type": "tool_result",
                    "tool": tool_name,
                    "summary": self._summarize_result(tool_name, tool_input, result),
                })

                tool_results.append({
                    "type": "tool_result",
                    "tool_use_id": block.id,
                    "content": json.dumps(result, default=str),
                })

            # Warn Claude to wrap up when close to the iteration limit
            if not done and iterations >= max(2, max_iterations - 4):
                tool_results.append({
                    "type": "text",
                    "text": (
                        f"⚠️ WRAP-UP REQUIRED: You have used {iterations} of {max_iterations} "
                        f"iterations and have {max_iterations - iterations} remaining. "
                        "Stop exploring — call finish_rca NOW using the evidence already gathered. "
                        "Do not call any other tools."
                    ),
                })

            messages.append({"role": "user", "content": tool_results})

            if done:
                break

        if final_report is None:
            # Last resort — ask Claude one final time with only finish_rca available
            logger.warning("Forcing final finish_rca call after %d iterations", iterations)
            forced_response = self.client.messages.create(
                model=settings.CLAUDE_MODEL,
                max_tokens=4096,
                system=SYSTEM_PROMPT,
                tools=TOOLS,
                messages=messages + [{
                    "role": "user",
                    "content": (
                        "You MUST call finish_rca right now. No more tool calls are allowed. "
                        "Use all the evidence gathered so far to produce the RCA report. "
                        "This is your final and only chance to submit."
                    ),
                }],
            )
            for block in forced_response.content:
                if getattr(block, "type", None) == "tool_use" and block.name == "finish_rca":
                    try:
                        self._dispatch(
                            "finish_rca", block.input, error_log, repo_info,
                            github_files_fetched, cache_hits, trace_callback,
                        )
                    except _FinishRCA as fin:
                        final_report = fin.report
                    break

        if final_report is None:
            raise RuntimeError(
                f"RCA agent did not call finish_rca after {iterations} iterations"
            )

        # Update metadata
        final_report.analysis_metadata.react_iterations = iterations
        final_report.analysis_metadata.github_files_fetched = github_files_fetched
        final_report.analysis_metadata.cache_hits = cache_hits
        final_report.analysis_metadata.deployment_record_used = repo_info.get(
            "deployment_record_used", False
        )
        final_report.analysis_metadata.repo_discovered_via = repo_info.get(
            "discovered_via", "unknown"
        )

        self._emit(trace_callback, {
            "type": "complete",
            "confidence": final_report.root_cause.confidence,
            "iterations": iterations,
        })

        # Persist to log_incidents (best-effort)
        self._persist(final_report, incident_id)
        return final_report

    # ── Tool dispatcher ───────────────────────────────────────────────────────

    def _summarize_result(self, tool_name: str, inp: dict, result: dict) -> str:
        if "error" in result:
            return f"Error from {tool_name}: {result['error']}"
        if tool_name == "get_repo_file":
            content = result.get("content", "")
            lines = len(content.split("\n")) if isinstance(content, str) else "?"
            return f"Fetched {lines} lines from {inp.get('path', '').split('/')[-1]}"
        if tool_name == "list_repo_files":
            items = result.get("files", [])
            return f"Listed {len(items) if isinstance(items, list) else '?'} items in {inp.get('directory', '/') or '/'}"
        if tool_name == "search_code_in_repo":
            items = result.get("results", [])
            return f"Found {len(items) if isinstance(items, list) else '?'} results for '{inp.get('query', '')}'"
        if tool_name == "get_commit_diff":
            files = result.get("files", [])
            additions = sum(f.get("additions", 0) for f in files) if isinstance(files, list) else 0
            deletions = sum(f.get("deletions", 0) for f in files) if isinstance(files, list) else 0
            return f"Commit diff: {len(files)} files (+{additions}/-{deletions})"
        if tool_name == "get_commits_since":
            commits = result.get("commits", [])
            return f"Found {len(commits) if isinstance(commits, list) else '?'} commits"
        if tool_name == "get_recent_deployments":
            deps = result.get("deployments", [])
            return f"Found {len(deps)} recent deployment(s)"
        if tool_name == "read_context_cache":
            return f"Cache {'hit' if result.get('cache_hit') else 'miss'}: {inp.get('cache_key', '')}"
        if tool_name == "write_context_cache":
            return f"Cached {inp.get('cache_key', '')}"
        return f"{tool_name} completed"

    def _dispatch(
        self,
        name: str,
        inp: dict,
        error_log,
        repo_info: dict,
        github_files_fetched: list[str],
        cache_hits: list[str],
        trace_callback: Callable[[dict], None] | None,
    ) -> dict:

        if name == "get_repo_file":
            path = inp["path"]
            result = get_repo_file(
                inp.get("org", repo_info["org"]),
                inp.get("repo", repo_info["repo"]),
                path,
                inp.get("ref", repo_info.get("commit_sha") or "main"),
            )
            if "error" not in result:
                github_files_fetched.append(path)
            return result

        if name == "list_repo_files":
            return list_repo_files(
                inp.get("org", repo_info["org"]),
                inp.get("repo", repo_info["repo"]),
                inp.get("directory", ""),
                inp.get("ref", repo_info.get("commit_sha") or "main"),
            )

        if name == "search_code_in_repo":
            return search_code_in_repo(
                inp.get("org", repo_info["org"]),
                inp.get("repo", repo_info["repo"]),
                inp["query"],
            )

        if name == "get_commit_diff":
            return get_commit_diff(
                inp.get("org", repo_info["org"]),
                inp.get("repo", repo_info["repo"]),
                inp["commit_sha"],
            )

        if name == "get_commits_since":
            return get_commits_since(
                inp.get("org", repo_info["org"]),
                inp.get("repo", repo_info["repo"]),
                inp["branch"],
                inp["since"],
            )

        if name == "get_recent_deployments":
            from datetime import timedelta
            since_hours = inp.get("since_hours", 48)
            since = datetime.now(timezone.utc) - timedelta(hours=since_hours)
            records = self.cicd.get_recent_deployments(
                inp["service_name"], inp["environment"], since, inp.get("limit", 5)
            )
            return {
                "deployments": [
                    {
                        "service_name": r.service_name,
                        "environment": r.environment,
                        "branch": r.branch,
                        "commit_sha": r.commit_sha,
                        "deployed_at": r.deployed_at.isoformat(),
                        "github_repo": r.github_repo,
                    }
                    for r in records
                ]
            }

        if name == "get_service_metadata":
            return self.obs.get_service_metadata(inp["service_name"])

        if name == "read_context_cache":
            cached = read_cache(inp["service_name"], inp["cache_key"])
            if cached is not None:
                cache_hits.append(inp["cache_key"])
                self._emit(trace_callback, {"type": "cache_hit", "key": inp["cache_key"]})
                return {"cache_hit": True, "content": cached}
            return {"cache_hit": False}

        if name == "write_context_cache":
            write_cache(
                inp["service_name"],
                inp["cache_key"],
                inp["content"],
                inp.get("commit_sha"),
            )
            return {"status": "cached"}

        if name == "finish_rca":
            report_data = inp.get("report", inp)
            report_data.setdefault("schema_version", "1.0")
            report_data.setdefault("rca_id", str(uuid.uuid4()))
            report_data.setdefault("error_log_id", error_log.id)
            report_data.setdefault("service_name", error_log.service_name)
            report_data.setdefault("generated_at", datetime.now(timezone.utc).isoformat())
            report_data.setdefault("analysis_metadata", {})
            report_data["analysis_metadata"]["github_files_fetched"] = github_files_fetched
            report_data["analysis_metadata"]["cache_hits"] = cache_hits
            report_data["analysis_metadata"]["model"] = settings.CLAUDE_MODEL
            report_data["analysis_metadata"].setdefault("react_iterations", 0)
            report_data["analysis_metadata"].setdefault("deployment_record_used", False)
            report_data["analysis_metadata"].setdefault("repo_discovered_via", "unknown")
            raise _FinishRCA(RCAReport(**report_data))

        logger.warning("Unknown tool: %s", name)
        return {"error": f"Unknown tool: {name}"}

    def _persist(self, report: RCAReport, incident_id: str) -> None:
        """Write RCA result back to log_incidents row (best-effort)."""
        try:
            from db.database import _get_conn, ensure_column
            ensure_column("rca_status", "VARCHAR(50)")
            ensure_column("rca_report", "MEDIUMTEXT")
            ensure_column("rca_error", "TEXT")

            conn = _get_conn()
            try:
                cur = conn.cursor()
                cur.execute(
                    "UPDATE log_incidents SET rca_status = 'completed', rca_report = %s "
                    "WHERE id = %s",
                    (json.dumps(report.model_dump(mode="json")), int(incident_id)),
                )
                conn.commit()
                cur.close()
            finally:
                conn.close()

            append_rca_history(report.service_name, {
                "rca_id": report.rca_id,
                "generated_at": report.generated_at,
                "root_cause_summary": report.root_cause.summary,
                "confidence": report.root_cause.confidence,
            })
        except Exception as exc:
            logger.warning("Could not persist RCA report: %s", exc)
